#!/usr/local/bin/python2.7
# encoding: utf-8
'''
@author:     Sid Probstein
@contact:    sidprobstein@gmail.com
'''

############################################"   
# codes for SDWIS

dictSDWISObjectives = {
    "B" : "DISINFECTION BY-PRODUCTS CONTROL",
    "C" : "CORROSION CONTROL",
    "D" : "DISINFECTION",
    "E" : "DECHLORINATION",
    "F" : "IRON REMOVAL",
    "I" : "INORGANICS REMOVAL",
    "M" : "MANGANESE REMOVAL",
    "O" : "ORGANICS REMOVAL",
    "P" : "PARTICULATE REMOVAL",
    "R" : "RADIONUCLIDES REMOVAL",
    "S" : "SOFTENING (HARDNESS REMOVAL)",
    "T" : "TASTE / ODOR CONTROL",
    "Z" : "OTHER"        
}
                       
dictSDWISTreatments = {
    "100" : "ACTIVATED ALUMINA",
    "121" : "ACTIVATED CARBON, GRANULAR",
    "125" : "ACTIVATED CARBON, POWDERED",
    "141" : "AERATION, CASCADE",
    "143" : "AERATION, DIFFUSED",
    "145" : "AERATION, PACKED TOWER",
    "147" : "AERATION, SLAT TRAY",
    "149" : "AERATION, SPRAY",
    "160" : "ALGAE CONTROL",
    "180" : "BONE CHAR",
    "190" : "BROMINIZATION (SPECIAL USE)",
    "200" : "CHLORAMINES",
    "220" : "CHLORINE DIOXIDE",
    "240" : "COAGULATION",
    "300" : "DISTILLATION",
    "320" : "ELECTRODIALYSIS",
    "341" : "FILTRATION, CARTRIDGE",
    "342" : "FILTRATION, DIATOMACEOUS EARTH",
    "343" : "FILTRATION, GREENSAND",
    "344" : "FILTRATION, PRESSURE SAND",
    "345" : "FILTRATION, RAPID SAND",
    "346" : "FILTRATION, SLOW SAND",
    "347" : "FILTRATION, ULTRAFILTRATION",
    "348" : "FILTERED",
    "360" : "FLOCCULATION",
    "380" : "FLUORIDATION",
    "401" : "GASEOUS CHLORINATION, POST",
    "403" : "GASEOUS CHLORINATION, PRE",
    "421" : "HYPOCHLORINATION, POST",
    "423" : "HYPOCHLORINATION, PRE",
    "441" : "INHIBITOR, BIMETALLIC PHOSPHATE",
    "443" : "INHIBITOR, HEXAMETAPHOSPHATE",
    "445" : "INHIBITOR, ORTHOPHOSPHATE",
    "447" : "INHIBITOR, POLYPHOSPHATE",
    "449" : "INHIBITOR, SILICATE",
    "455" : "IODINE",
    "460" : "ION EXCHANGE",
    "461" : "CHLORINATION (FRDS-1.5)",
    "473" : "CONVERTED (FRDS-1.5)",
    "500" : "LIME - SODA ASH ADDITION",
    "520" : "MICROSCREENING",
    "541" : "OZONATION, POST",
    "543" : "OZONATION, PRE",
    "560" : "PERMANGANATE",
    "580" : "PEROXIDE",
    "600" : "RAPID MIX",
    "620" : "REDUCING AGENTS",
    "623" : "REDUCING AGENT, SODIUM BISULFATE",
    "625" : "REDUCING AGENT, SODIUM SULFITE",
    "627" : "REDUCING AGENT, SULFUR DIOXIDE",
    "640" : "REVERSE OSMOSIS",
    "660" : "SEDIMENTATION",
    "680" : "SEQUESTRATION",
    "700" : "SLUDGE TREATMENT",
    "720" : "ULTRAVIOLET RADIATION",
    "740" : "PH ADJUSTMENT",
    "741" : "PH ADJUSTMENT, POST",
    "742" : "PH ADJUSTMENT, PRE"
}
